@startuml End-User Module - Timetable Module

title End-User Module - Timetable Module
left to right direction


' Actors
"End-user" as EU
Student --|> EU
Lecturer --|> EU


' Use Cases
rectangle "UTM FC Scheduler - End User Module" {

package "B - Timetable Module" {
    ' CRUD Timetable operation
    usecase (FR_ABA_01 \n Create Timetable) as FR_ABA_01
    usecase (FR_ABA_02 \n Update Timetable) as FR_ABA_02
    usecase (FR_ABA_03 \n Delete Timetable) as FR_ABA_03
    usecase (FR_ABA_04 \n View Timetable) as FR_ABA_04

    usecase (FR_ABB_01 \n Export Timetable) as FR_ABB_01
    usecase (FR_ABB_02 \n Import Timetable) as FR_ABB_02

    usecase (FR_ABC_01 \n Clash Checking) as FR_ABC_01

    usecase (FR_ABD_01 \n Generate Timetable) as FR_ABD_01
    usecase (FR_ABD_02 \n Configure Generation Preferences) as FR_ABD_02
}
}

' Associations
EU -- FR_ABA_01
EU -- FR_ABA_02
EU -- FR_ABA_03
EU -- FR_ABA_04
EU -- FR_ABB_01
EU -- FR_ABB_02
FR_ABB_01 ..> FR_ABC_01 : <<includes>>
FR_ABB_02 ..> FR_ABC_01 : <<includes>>
EU -- FR_ABD_01
FR_ABD_01 <.. FR_ABD_02 : <<extends>>
FR_ABD_01 ..> FR_ABC_01 : <<includes>>

@enduml