@startuml FR_BDA_01
title FR_BCA_01 - Add Lecturer


|#gold|eu| Academic office staff
|#palegreen|sys| UTM FC Scheduler

|eu|
start
:The academic office staff clicks the "New Lecturer" button;

|sys|
:The system creates a new lecturer instance;
:A successful snack-bar message will be displayed;

stop

@enduml
