@startuml FR_BFA_01
title FR_BFA_01 - Add Course


|#gold|eu| Academic office staff
|#palegreen|sys| UTM FC Scheduler

|eu|
start
:The academic office staff clicks the "New Course" button;

|sys|
:The system creates a new course;
:A successful snack-bar message will be displayed;

stop

@enduml
