@startuml Use Case Diagram - End-User Module

title Use Case Diagram - End-User Module
left to right direction

' Use case ID format: FR_ABC_00
' FR: Functional Requirement
' A: Module. A for End-User, B for Academic Office Staff
' B: Sub-module
' C: Sub-module group
' 00: Use case number


' Actors
"End-user" as EU
Student --|> EU
Lecturer --|> EU


' Use Cases
rectangle "UTM FC Scheduler - End User Module" {
    package "A - Auth Module" {
        usecase (FR_AAA_01 \n Login) as FR_AAA_01
        usecase (FR_AAA_02 \n Logout) as FR_AAA_02
    }


    package "B - Timetable Module" {
        ' CRUD Timetable operation
        usecase (FR_ABA_01 \n Create Timetable) as FR_ABA_01
        usecase (FR_ABA_02 \n Update Timetable) as FR_ABA_02
        usecase (FR_ABA_03 \n Delete Timetable) as FR_ABA_03
        usecase (FR_ABA_04 \n View Timetable) as FR_ABA_04

        usecase (FR_ABB_01 \n Export Timetable) as FR_ABB_01
        usecase (FR_ABB_02 \n Import Timetable) as FR_ABB_02

        usecase (FR_ABC_01 \n Clash Checking) as FR_ABC_01

        usecase (FR_ABD_01 \n Generate Timetable) as FR_ABD_01
        usecase (FR_ABD_02 \n Configure Generation Preferences) as FR_ABD_02
    }



    package "C - Course Module" {
        ' CRUD Course operation
        usecase (FR_ACA_01 \n Create Course) as FR_ACA_01
        usecase (FR_ACA_02 \n Update Course) as FR_ACA_02
        usecase (FR_ACA_03 \n Delete Course) as FR_ACA_03
        usecase (FR_ACA_04 \n View Course) as FR_ACA_04

        ' CRUD Course Notifier operation
        usecase (FR_ACB_01 \n Add Course Notifier) as FR_ACB_01
        usecase (FR_ACB_02 \n Remove Course Notifier) as FR_ACB_02
        usecase (FR_ACB_03 \n View Course Notifier) as FR_ACB_03

        ' Alternative add course operation
        usecase (FR_ACC_01 \n Browse & Add Offered Courses) as FR_ACC_01
        usecase (FR_ACC_02 \n Retrieve Registered Courses - Lecturer) as FR_ACC_02
        usecase (FR_ACC_03 \n Retrieve Registered Courses - Student) as FR_ACC_03
    }

    
    package "D - Class Module" {
        ' CRUD Class operation
        usecase (FR_ADA_01 \n Create Class) as FR_ADA_01
        usecase (FR_ADA_02 \n Update Class) as FR_ADA_02
        usecase (FR_ADA_03 \n Delete Class) as FR_ADA_03
        usecase (FR_ADA_04 \n View Class) as FR_ADA_04
    }
}

' Associations
EU -- FR_AAA_01
EU -- FR_AAA_02

EU -- FR_ABA_01
EU -- FR_ABA_02
EU -- FR_ABA_03
EU -- FR_ABA_04
EU -- FR_ABB_01
EU -- FR_ABB_02
FR_ABB_01 ..> FR_ABC_01 : <<includes>>
FR_ABB_02 ..> FR_ABC_01 : <<includes>>
EU -- FR_ABD_01
FR_ABD_01 <.. FR_ABD_02 : <<extends>>
FR_ABD_01 ..> FR_ABC_01 : <<includes>>

EU -- FR_ACA_01
EU -- FR_ACA_02
EU -- FR_ACA_03
EU -- FR_ACA_04
EU -- FR_ACB_01
EU -- FR_ACB_02
EU -- FR_ACB_03
FR_ACA_01 <.. FR_ACC_01 : <<extends>>
FR_ACA_01 <.. FR_ACC_02 : <<extends>>
FR_ACA_01 <.. FR_ACC_03 : <<extends>>

EU -- FR_ADA_01
EU -- FR_ADA_02
EU -- FR_ADA_03
EU -- FR_ADA_04

@enduml