@startuml FR_ABA_03
title FR_ABA_03 - Delete Timetable
skinparam maxMessageSize 125

actor "End User" as eu
boundary "Timetable Page" as fe
' control "TimetableController" as ct
' entity "Timetable" as en
' database "Database" as db

activate eu

eu -> fe ++ : Click on the Delete button on the timetable to delete
fe -> fe : showConfirmationDialog(msg)
eu -> fe : Click on the Confirm button

fe -> fe : deleteTimetable(id)
fe -> fe : hideConfirmationDialog()
fe -> fe -- : showSuccessSnackbar(msg)

alt Cancel
    eu -> fe ++ : Click on the Cancel button
    fe -> fe : hideConfirmationDialog()
end



deactivate eu

@enduml