@startuml FR_AAA_02
title FR_AAA_02 - Logout
skinparam maxMessageSize 125

actor "End User" as eu
boundary MainPage as fe
control AuthController as ct
' entity Entity as en
database Database as db

activate eu

eu -> fe ++ : Click Sign out button
fe -> fe : showLoadingIndicator()

fe -> ct ++ : logout()
ct -> db ++ : deleteSession()
return result
ct -> fe : onLogoutSuccess()
fe -> fe : hideLoadingIndicator()
fe -> fe : showSuccessSnackbar(msg)
fe -> fe : redirectToMainPage()

alt Invalid sign out
    ct -> fe : onLogoutFailure()
    fe -> fe : showErrorSnackbar(msg)
end

deactivate eu

@enduml