@startuml FR_BGA_01
title FR_BGA_01 - Add Section
skinparam maxMessageSize 125

actor "Academic Office Staff" as eu
boundary "Sections Page" as fe
control "SectionController" as ct

database "Database" as db

activate eu

eu -> fe ++ : Clicks on New Section button
fe -> ct ++ : createNewSection()
ct -> db ++ : save(section)
db --> ct -- : section
ct --> fe -- : section
fe -> fe : showSuccessSnackbar(msg)

deactivate eu

@enduml