@startuml FR_BGA_03
title FR_BGA_03 - Delete Section
skinparam maxMessageSize 125

actor "Academic Office Staff" as eu
boundary "Sections Page" as fe
control "SectionController" as ct
database "Database" as db

activate eu

eu -> fe ++ : Clicks on Delete button of section
fe -> fe : showConfirmationDialog(msg)
eu -> fe : Click on the Confirm button

fe -> ct ++ : deleteSection(id)
ct -> db ++ : deleteSection(id)
db --> ct -- : Section deleted
ct --> fe -- : Section deleted
fe -> fe : onDeleted()
fe -> fe : closeConfirmationDialog()
fe -> fe -- : showSuccessSnackbar(msg)

alt Cancel
    eu -> fe ++ : Click on the Cancel button
    fe -> fe : hideConfirmationDialog()
end



deactivate eu

@enduml