@startuml FR_BFA_01
title FR_BFA_01 - Add Course
skinparam maxMessageSize 125

actor "Academic Office Staff" as eu
boundary "Courses Page" as fe
control "CourseController" as ct

database "Database" as db

activate eu

eu -> fe ++ : Clicks on New Course button
fe -> ct ++ : createNewCourse()
ct -> db ++ : save(course)
db --> ct -- : course
ct --> fe -- : course
fe -> fe : showSuccessSnackbar(msg)

deactivate eu

@enduml