@startuml FR_BDA_01
title FR_BDA_01 - Add Lecturer
skinparam maxMessageSize 125

actor "Academic Office Staff" as eu
boundary "Lecturers Page" as fe
control "LecturerController" as ct

database "Database" as db

activate eu

eu -> fe ++ : Clicks on New Lecturer button
fe -> ct ++ : createNewLecturer()
ct -> db ++ : save(lecturer)
db --> ct -- : lecturer
ct --> fe -- : lecturer
fe -> fe : showSuccessSnackbar(msg)

deactivate eu

@enduml