@startuml FR_BEA_01
title FR_BEA_01 - Add Test Case
skinparam maxMessageSize 125

actor "Academic Office Staff" as eu
boundary "Test Cases Page" as fe
control "TestCaseController" as ct

database "Database" as db

activate eu

eu -> fe ++ : Clicks on New Test Case button
fe -> ct ++ : createNewTestCase()
ct -> db ++ : save(testCase)
db --> ct -- : testCase
ct --> fe -- : testCase
fe -> fe : showSuccessSnackbar(msg)

deactivate eu

@enduml