@startuml FR_BHA_01
title FR_BHA_01 - Add Class
skinparam maxMessageSize 125

actor "Academic Office Staff" as eu
boundary "Section Page" as fe
control "ClassController" as ct

database "Database" as db

activate eu

eu -> fe ++ : Clicks on New Class button
fe -> ct ++ : createNewClass()
ct -> db ++ : save(class)
db --> ct -- : class
ct --> fe -- : class
fe -> fe : showSuccessSnackbar(msg)

deactivate eu

@enduml