@startuml FR_BBA_01
title FR_BBA_01 - Add Session Semester
skinparam maxMessageSize 125

actor "Academic Office Staff" as eu
boundary "Session Semesters Page" as fe
control "SessionSemesterController" as ct

database "Database" as db

activate eu

eu -> fe ++ : Clicks on New Session Semester button
fe -> ct ++ : createNewSessionSemester()
ct -> db ++ : save(sessionSemester)
db --> ct -- : sessionSemester
ct --> fe -- : sessionSemester
fe -> fe : showSuccessSnackbar(msg)

deactivate eu

@enduml