@startuml FR_ACC_03
title Retrieve Registered Courses - Student


|#gold|eu| Student
|#palegreen|sys| UTM FC Scheduler

|eu|
start

:The student clicks on the "Retrieve courses" button;

|sys|
:The system displays the "Retrieve courses (Student)" model window,
which initially has a list of session semesters;

|eu|
:The student selects the session semester;

|sys|
:The modal window displays a list of registered subjects of the
selected semester by said student;

|eu|
if (cancel?) then (yes)
    :The student clicks on the "Cancel" button;
    :The system closes the confirmation modal window;
else (no)
    :The lecturer clicks on the "Confirm" button;
    |sys|
    :The system adds the registered courses;
    :The system displays a successful snack-bar message;
    :The system closes the confirmation modal window;
endif

|eu|
stop
@enduml
