@startuml FR_ADA_02
title FR_ADA_02 - Update Class


|#gold|eu| End users
|#palegreen|sys| UTM FC Scheduler

|eu|
start

|eu|
(A)
:The user edits the class information;
:The user clicks on the "Save" button;

|sys|
if (invalid input?) then (yes)
    :The system displays an invalid input snack-bar message;
    (A)
    detach
else (no)
endif

|sys|
:The system displays a successful snack-bar message;

stop

@enduml
