@startuml Academic Office Staff Module - Auth Module

title Academic Office Staff Module - Auth Module
left to right direction

' Use case ID format: FR_BBC_00
' FR: Functional Requirement
' A: Module. A for End-User, B for Academic Office Staff
' B: Sub-module
' C: Sub-module group
' 00: Use case number


' Actors
"Academic Office Staff" as AOS

' Use Cases
rectangle "UTM FC Scheduler - Academic Office Staff Module" {
package "A - Auth Module" {
    usecase (FR_BAA_01 \n Login) as FR_BAA_01
    usecase (FR_BAA_02 \n Logout) as FR_BAA_02
}
}

' Associations
AOS -- FR_BAA_01
AOS -- FR_BAA_02

@enduml