@startuml Academic Office Staff Module - Class Module

title Academic Office Staff Module - Class Module
left to right direction

' Use case ID format: FR_BBC_00
' FR: Functional Requirement
' A: Module. A for End-User, B for Academic Office Staff
' B: Sub-module
' C: Sub-module group
' 00: Use case number


' Actors
"Academic Office Staff" as AOS

' Use Cases
rectangle "UTM FC Scheduler - Academic Office Staff Module" {
    usecase (FR_BBC_01 \n Clash checking) as FR_BBC_01

    package "H - Class Module" {
        usecase (FR_BHA_01 \n Add Class) as FR_BHA_01
        usecase (FR_BHA_02 \n Edit Class) as FR_BHA_02
        usecase (FR_BHA_03 \n Delete Class) as FR_BHA_03
        usecase (FR_BHA_04 \n View Class) as FR_BHA_04
    }
}

' Associations
AOS -- FR_BHA_01
AOS -- FR_BHA_02
AOS -- FR_BHA_03
AOS -- FR_BHA_04
FR_BHA_01 <.. FR_BBC_01 : <<include>>
FR_BHA_02 <.. FR_BBC_01 : <<include>>

@enduml