@startuml Academic Office Staff Module - Section Module

title Academic Office Staff Module - Section Module
left to right direction

' Use case ID format: FR_BBC_00
' FR: Functional Requirement
' A: Module. A for End-User, B for Academic Office Staff
' B: Sub-module
' C: Sub-module group
' 00: Use case number


' Actors
"Academic Office Staff" as AOS

' Use Cases
rectangle "UTM FC Scheduler - Academic Office Staff Module" {
    package "G - Section Module" {
        usecase (FR_BGA_01 \n Add Section) as FR_BGA_01
        usecase (FR_BGA_02 \n Edit Section) as FR_BGA_02
        usecase (FR_BGA_03 \n Delete Section) as FR_BGA_03
        usecase (FR_BGA_04 \n View Section) as FR_BGA_04
    }
}

' Associations
AOS -- FR_BGA_01
AOS -- FR_BGA_02
AOS -- FR_BGA_03
AOS -- FR_BGA_04
@enduml